"""empty message

Revision ID: 42bfe2eea012
Revises: a30cfdb3f4e0
Create Date: 2020-08-17 23:32:27.466566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42bfe2eea012'
down_revision = 'a30cfdb3f4e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('height', sa.Float(precision=2), nullable=True))
    op.add_column('players', sa.Column('weight', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'weight')
    op.drop_column('players', 'height')
    # ### end Alembic commands ###
