"""empty message

Revision ID: 7063ba433f61
Revises: 9083a7b0ece3
Create Date: 2020-08-17 23:36:51.773124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7063ba433f61'
down_revision = '9083a7b0ece3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('position', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'position')
    # ### end Alembic commands ###
