"""empty message

Revision ID: 7608ebbc17b3
Revises: fa572937f8fb
Create Date: 2020-08-11 21:16:00.347425

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7608ebbc17b3'
down_revision = 'fa572937f8fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('uniform_one', sa.String(length=300), nullable=True))
    op.add_column('teams', sa.Column('uniform_two', sa.String(length=300), nullable=True))
    op.drop_column('teams', 't_shirt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('t_shirt', mysql.VARCHAR(length=300), nullable=True))
    op.drop_column('teams', 'uniform_two')
    op.drop_column('teams', 'uniform_one')
    # ### end Alembic commands ###
