"""empty message

Revision ID: 9083a7b0ece3
Revises: 42bfe2eea012
Create Date: 2020-08-17 23:34:07.005243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9083a7b0ece3'
down_revision = '42bfe2eea012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('country', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'country')
    # ### end Alembic commands ###
