"""empty message

Revision ID: a30cfdb3f4e0
Revises: c82e8b01a231
Create Date: 2020-08-16 23:12:32.573527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a30cfdb3f4e0'
down_revision = 'c82e8b01a231'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('country', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'country')
    # ### end Alembic commands ###
